#213 set maximum build count to display in the archives section
prashanth-sams/pytest-html-reporter pull request #214
Opened 2022-04-08 21:32 UTC by prashanth-sams

# Merge checklist
- [ ] TravisCI tests passed
- [ ] Documentation

2022-04-08 21:34 UTC, prashanth-sams commented
note: will fix the issues mentioned in linter

2022-04-08 21:43 UTC, prashanth-sams commented
note: will add unit test for this module

2022-04-10 13:14 UTC, kozakHolota requested changes

2022-04-10 15:03 UTC, prashanth-sams commented on pytest_html_reporter/util.py
> +def remove_old_archives(path, archive_count):
@kozakHolota moved inside the HTMLReporter

2022-04-10 15:08 UTC, prashanth-sams commented on pytest_html_reporter/html_reporter.py
> +    def __init__(self, path, archive_count, config):
> Archive count make as a command line option with some default
- Yeah I already have that snippet in `pytest_addoption` method 
```
group.addoption(
        "--archive-count",
        action="store",
        dest="archive_count",
        default="",
        help="set maximum build count to display in the archives section",
    )
```

> During HTMLReporter init just take the cmd param value and set this as the archive_count attribute value?
- I think I did the same - not sure if I am right. can you please give me the snippet for as a rough idea

2022-04-11 07:11 UTC, prashanth-sams commented on pytest_html_reporter/html_reporter.py
> +    def __init__(self, path, archive_count, config):
I actually set empty string as default purposely; cos, we allow archives by default.

2022-04-11 07:19 UTC, merged